   on:
    #  schedule:
    #    - cron: '0 2 * * *'  # Daily at 2 AM UTC
     workflow_dispatch:

   permissions:
     contents: read
     security-events: write

   jobs:
     security-scan:
       name: Daily Security Scan
       runs-on: ubuntu-latest
       
       steps:
       - name: Checkout code
         uses: actions/checkout@v4

       - name: Run Trivy
         uses: aquasecurity/trivy-action@master
         with:
           scan-type: 'fs'
           format: 'sarif'
           output: 'trivy-results.sarif'

       - name: Upload Trivy results
         uses: github/codeql-action/upload-sarif@v3
         with:
           sarif_file: 'trivy-results.sarif'

       - name: Scan images
         uses: aquasecurity/trivy-action@master
         with:
           image-ref: 'ollama/ollama:latest'
           format: 'sarif'
           output: 'trivy-image-results.sarif'

       - name: Upload image scan results
         uses: github/codeql-action/upload-sarif@v3
         with:
           sarif_file: 'trivy-image-results.sarif'

       - name: Send Slack notification
         if: failure()
         uses: slackapi/slack-github-action@v1.25.0
         with:
           payload: |
             {
               "text": "⚠️ Security Scan Detected Issues",
               "blocks": [
                 {
                   "type": "section",
                   "text": {
                     "type": "mrkdwn",
                     "text": "*Daily Security Scan Alert*\n❌ Vulnerabilities detected\nPlease review GitHub Security tab"
                   }
                 }
               ]
             }
         env:
           SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
           SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK